name: dont_forget
description: "A new Flutter project."
publish_to: 'none'
version: 1.5.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  intl: ^0.20.3
  image_picker: ^1.1.2
  record: ^4.4.4
  audioplayers: ^5.2.1
  flutter_local_notifications: ^17.2.1
  uuid: ^4.4.4
  timezone: ^0.9.4
  sqlite3_flutter_libs: ^0.6.0+eol
  window_manager: ^0.5.2
  tray_manager: ^0.5.3
  file_picker: ^12.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon.ico
    - assets/app_icon.png
